# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

S_brute_force <- function(f, alpha, fst = 0) {
    .Call('_numberofalleles_S_brute_force', PACKAGE = 'numberofalleles', f, alpha, fst)
}

is_equal <- function(x, y) {
    .Call('_numberofalleles_is_equal', PACKAGE = 'numberofalleles', x, y)
}

S_recursive <- function(f, alpha, fst) {
    .Call('_numberofalleles_S_recursive', PACKAGE = 'numberofalleles', f, alpha, fst)
}

pr_mixture_given_n_independent_alleles <- function(number_of_independent_alleles, theta, R, f) {
    .Call('_numberofalleles_pr_mixture_given_n_independent_alleles', PACKAGE = 'numberofalleles', number_of_independent_alleles, theta, R, f)
}

pr_mixtures_given_n_independent_alleles <- function(number_of_independent_alleles, theta, mixtures, f) {
    .Call('_numberofalleles_pr_mixtures_given_n_independent_alleles', PACKAGE = 'numberofalleles', number_of_independent_alleles, theta, mixtures, f)
}

pr_k_allele_mixtures <- function(x, f) {
    .Call('_numberofalleles_pr_k_allele_mixtures', PACKAGE = 'numberofalleles', x, f)
}

pr_num_distinct_multi_pop <- function(f, num_indep_by_pop) {
    .Call('_numberofalleles_pr_num_distinct_multi_pop', PACKAGE = 'numberofalleles', f, num_indep_by_pop)
}

pr_num_distinct_multi_pop2 <- function(f, num_indep_by_pop) {
    .Call('_numberofalleles_pr_num_distinct_multi_pop2', PACKAGE = 'numberofalleles', f, num_indep_by_pop)
}

pr_sum <- function(x1, fx1, x2, fx2) {
    .Call('_numberofalleles_pr_sum', PACKAGE = 'numberofalleles', x1, fx1, x2, fx2)
}

get_set_bits <- function(mask) {
    .Call('_numberofalleles_get_set_bits', PACKAGE = 'numberofalleles', mask)
}

sample_mixture_masks_number_of_independent_alleles_locus <- function(freqs_locus, number_of_indep_alleles, number_of_samples) {
    .Call('_numberofalleles_sample_mixture_masks_number_of_independent_alleles_locus', PACKAGE = 'numberofalleles', freqs_locus, number_of_indep_alleles, number_of_samples)
}

sample_mixture_alleles_locus <- function(freqs_locus, number_of_contributors, number_of_samples) {
    .Call('_numberofalleles_sample_mixture_alleles_locus', PACKAGE = 'numberofalleles', freqs_locus, number_of_contributors, number_of_samples)
}

sample_allele_count_locus <- function(freqs_locus, number_of_contributors, number_of_samples) {
    .Call('_numberofalleles_sample_allele_count_locus', PACKAGE = 'numberofalleles', freqs_locus, number_of_contributors, number_of_samples)
}

sample_allele_count_num_indep_alleles_locus <- function(freqs_locus, number_of_indep_alleles, number_of_samples) {
    .Call('_numberofalleles_sample_allele_count_num_indep_alleles_locus', PACKAGE = 'numberofalleles', freqs_locus, number_of_indep_alleles, number_of_samples)
}

sample_k_allele_mixtures_brute_force <- function(freqs_locus, number_of_alleles, number_of_samples) {
    .Call('_numberofalleles_sample_k_allele_mixtures_brute_force', PACKAGE = 'numberofalleles', freqs_locus, number_of_alleles, number_of_samples)
}

sample_k_allele_mixtures <- function(freqs_locus, number_of_alleles, number_of_samples) {
    .Call('_numberofalleles_sample_k_allele_mixtures', PACKAGE = 'numberofalleles', freqs_locus, number_of_alleles, number_of_samples)
}

sample_k_allele_mixtures_uniform <- function(freqs_locus, number_of_alleles, number_of_samples) {
    .Call('_numberofalleles_sample_k_allele_mixtures_uniform', PACKAGE = 'numberofalleles', freqs_locus, number_of_alleles, number_of_samples)
}

weights_cpp <- function(x) {
    .Call('_numberofalleles_weights_cpp', PACKAGE = 'numberofalleles', x)
}

