# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

S_brute_force <- function(f, alpha) {
    .Call('_numberofalleles_S_brute_force', PACKAGE = 'numberofalleles', f, alpha)
}

is_equal <- function(x, y) {
    .Call('_numberofalleles_is_equal', PACKAGE = 'numberofalleles', x, y)
}

S_recursive <- function(f, alpha) {
    .Call('_numberofalleles_S_recursive', PACKAGE = 'numberofalleles', f, alpha)
}

pr_sum <- function(x1, fx1, x2, fx2) {
    .Call('_numberofalleles_pr_sum', PACKAGE = 'numberofalleles', x1, fx1, x2, fx2)
}

