# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Sbruteforce <- function(f, alpha) {
    .Call('_numberofalleles_Sbruteforce', PACKAGE = 'numberofalleles', f, alpha)
}

rcpp_hello_world <- function() {
    .Call('_numberofalleles_rcpp_hello_world', PACKAGE = 'numberofalleles')
}

